# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
- group: springbootdeploys

pool:
  vmImage: 18.0.2.1-jdk-slim-buster

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script:
   ./mvnw spring-boot:build-image
  displayName: build docker container with maiven  
   
- script:
   docker login     
   $(DOCKERHUB_PASS)
  displayName: login to dockerhub

- script:
   docker tag e20223f10e8a jaguarjs/firstjavaserver:2

- script:
   docker push jaguarjs/firstjavaserver:2

